# Regenerates Resources/Dictionary.Designer.cs from Dictionary.resx, replicating the
# StronglyTypedResourceBuilder output (public class, alphabetical properties, "similar
# to '<key>'" comment for multi-line values). UTF-8 without BOM.
#
# WHY THIS EXISTS: `dotnet build` only compiles the .resx into .resources — the strongly
# typed Designer.cs is regenerated by the Visual Studio custom tool (ResXFileCodeGenerator)
# when the resx is saved. After editing any Dictionary.*.resx from the CLI, run this to
# keep Dictionary.Designer.cs in sync (otherwise the new Dictionary.* members are missing).
#
# Usage:  powershell -NoProfile -ExecutionPolicy Bypass -File scripts\regenerate-dictionary-designer.ps1
param()
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)   # scripts/ → repo root
$resx = Join-Path $repo 'Resources\Dictionary.resx'
$out = Join-Path $repo 'Resources\Dictionary.Designer.cs'
$xmlText = [System.IO.File]::ReadAllText($resx, [System.Text.Encoding]::UTF8)
[xml]$doc = $xmlText
$names = @($doc.root.data | ForEach-Object { $_.name } | Sort-Object)
$sb = New-Object System.Text.StringBuilder
function L([string]$s) { [void]$sb.AppendLine($s) }
L '//------------------------------------------------------------------------------'
L '// <auto-generated>'
L '//     This code was generated by a tool.'
L '//'
L '//     Changes to this file may cause incorrect behavior and will be lost if'
L '//     the code is regenerated.'
L '// </auto-generated>'
L '//------------------------------------------------------------------------------'
L ''
L 'namespace AgentBridge.Resources {'
L ''
L '    /// <summary>'
L '    ///   A strongly-typed resource class, for looking up localized strings, etc.'
L '    /// </summary>'
L '    // This class was auto-generated by the StronglyTypedResourceBuilder'
L '    // class via a tool like ResGen or Visual Studio.'
L '    // To add or remove a member, edit your .ResX file then rerun ResGen'
L '    // with the /str option, or rebuild your VS project.'
L '    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]'
L '    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]'
L '    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]'
L '    public class Dictionary {'
L ''
L '        private static global::System.Resources.ResourceManager resourceMan;'
L ''
L '        private static global::System.Globalization.CultureInfo resourceCulture;'
L ''
L '        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]'
L '        internal Dictionary() {'
L '        }'
L ''
L '        /// <summary>'
L '        ///   Returns the cached ResourceManager instance used by this class.'
L '        /// </summary>'
L '        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]'
L '        public static global::System.Resources.ResourceManager ResourceManager {'
L '            get {'
L '                if (object.ReferenceEquals(resourceMan, null)) {'
L '                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentBridge.Resources.Dictionary", typeof(Dictionary).Assembly);'
L '                    resourceMan = temp;'
L '                }'
L '                return resourceMan;'
L '            }'
L '        }'
L ''
L '        /// <summary>'
L '        ///   Overrides the current thread''s CurrentUICulture property for all'
L '        ///   resource lookups using this strongly typed resource class.'
L '        /// </summary>'
L '        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]'
L '        public static global::System.Globalization.CultureInfo Culture {'
L '            get {'
L '                return resourceCulture;'
L '            }'
L '            set {'
L '                resourceCulture = value;'
L '            }'
L '        }'
foreach ($n in $names) {
    $val = ($doc.root.data | Where-Object { $_.name -eq $n } | Select-Object -First 1).value
    $text = if ($val -match "`n") { $n } else { $val }
    L ''
    L '        /// <summary>'
    L "        ///   Looks up a localized string similar to '$text'."
    L '        /// </summary>'
    L "        public static string $n {"
    L '            get {'
    L "                return ResourceManager.GetString(""$n"", resourceCulture);"
    L '            }'
    L '        }'
}
L '    }'
L '}'
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "Regenerated $out with $($names.Count) resources"
